### ISSUE TITLE
question: modifying the training set for intuitionistic propositional logic?

### ISSUE THREAD

**Issue by vcvpaiva** [deepmind/logical-entailment-dataset#2]
hi,  a question here:
if I remember correctly the paper mentions "other logics". 
did you try changing the construction process to produce 'intuitionistic propositional logic' instead of classical logic?
Thanks
Valeria

**Comment by RichardEvans** [comment]
No, we haven't tried that.

But I agree it would be interesting to do intuitionistic logic and see how
the results compare.

**Comment by vcvpaiva** [comment]
thanks for the prompt reply!
